"""Prompt-bank extension: the diversity fix FINDINGS §7 item 0b calls a blocker.

96 prompts / 432 clips is what v5 trained on, and it is the stated reason the
rolling-K/V work improved world_p0 and failed to generalise to the other three
worlds. At effective batch 64 the old bank is nine iterations per epoch. This
module adds 904 prompts to reach 1000.

TWO RULES THIS FILE FOLLOWS, AND WHY.

1. **It never touches indices 0-95.** `prompts.py` keeps its original bank
   verbatim and `prompt_bank()` appends this module afterwards, so prompt 0 is
   still the talking head, 44 the owl, 60 the waterfall and 82 the court. Those
   four are `out/world_p{0,44,60,82}.pt` and every 1:1 comparison in FINDINGS;
   renumbering them would silently invalidate the entire before/after evaluation
   and the teacher clips already generated for them.

2. **Same composition discipline as the original.** Stable subject, continuous
   non-cut motion, one scene per prompt. No hard cuts, no crowds, no rapid scene
   changes -- a block-causal model with a sliding K/V window cannot represent
   them, so training on them teaches nothing it can keep. Roughly half remains
   human subjects for the interaction use case.

What is deliberately WIDER than the original bank, since narrowness was the
defect being fixed: many more trades, activities and interiors; the same kind of
subject under different times of day, weather and light; more variation in
framing distance, in how much of the frame the subject occupies, and in how fast
the motion is. Content type, lighting and setting vary as independently as a
hand-written list can manage, so the student does not learn that (say) a
workshop implies warm light.
"""

# --------------------------------------------------------------------- people
# Direct-to-camera and conversational. The papers' interaction case, and the
# thing mid-stream text switching will eventually have to stay inside, so it is
# the largest single block.
TALKING = [
    "A woman in a green blouse speaking to the camera and pausing to think, soft key light, plain grey backdrop",
    "A man with round glasses explaining something to the camera, hands moving in front of him, warm office lighting",
    "A young man in a hooded sweatshirt talking casually to the camera, bedroom behind him, string lights out of focus",
    "A woman with short silver hair speaking calmly from an armchair, window light from the right, quiet room",
    "A man with a full beard laughing mid-sentence while talking to the camera, kitchen background, morning light",
    "A woman in a blazer presenting to the camera with confident posture, softbox lighting, dark backdrop",
    "A man in a plaid shirt leaning forward as he speaks, workshop behind him, overhead work lights",
    "A woman with braided hair nodding and answering, cafe table, afternoon light through a window",
    "A man in a turtleneck speaking quietly to the camera, dim room, a single lamp to one side",
    "A woman in hospital scrubs talking to the camera, corridor blurred behind her, cool ceiling light",
    "A man in a denim jacket gesturing while telling a story, brick wall behind, late afternoon sun",
    "A woman with freckles smiling and speaking, close framing, natural window light, white wall",
    "An older man in a cardigan speaking slowly and thoughtfully, bookshelves behind, warm reading lamp",
    "A woman in a striped shirt raising her eyebrows as she makes a point, soft even studio light",
    "A man with a shaved head speaking directly to camera, arms folded, grey seamless background",
    "A woman in a knitted jumper cupping a mug while talking, sofa, soft lamp light, evening",
    "A young woman with glasses reading aloud and glancing up at the camera, desk lamp, dark room",
    "A man in a chef's jacket describing something to the camera, stainless kitchen behind, bright light",
    "A woman in a high-collared coat speaking outdoors, breath faintly visible, overcast winter light",
    "A man seated at a desk turning from a monitor to speak to the camera, blue screen glow on his face",
    "A woman with long red hair tilting her head while listening, soft rim light, dark background",
    "A man in a linen shirt speaking on a balcony, sea out of focus behind him, bright midday sun",
    "A woman in a lab coat explaining a result to the camera, whiteboard behind, fluorescent light",
    "An older woman with reading glasses on a chain speaking warmly, conservatory, filtered daylight",
    "A man in a mechanic's overall wiping his hands while talking, garage, harsh overhead lamp",
    "A woman in a silk scarf speaking with animated expressions, hotel lobby, warm ambient light",
    "A young man with curly hair pausing and starting again mid-sentence, plain wall, flat daylight",
    "A woman in a puffer jacket talking to the camera in falling snow, grey afternoon light",
    "A man in a suit jacket without a tie speaking calmly, glass office, city blurred behind",
    "A woman with a nose ring smiling and speaking, record shop behind her, warm tungsten light",
    "A man in a fleece speaking from inside a tent doorway, dawn light on the fabric",
    "A woman in a black polo neck speaking to camera in profile then turning to face it, dramatic side light",
    "A man in a rugby shirt talking while catching his breath, park behind him, bright overcast sky",
    "A woman in a tailored coat speaking on a station platform, train lights behind, evening",
    "An older man with a walking stick seated on a bench, speaking to the camera, dappled park light",
    "A woman in a chef's apron tasting from a spoon then talking to the camera, warm kitchen light",
    "A man with a moustache speaking while leaning against a doorframe, hallway light behind him",
    "A woman in a summer dress speaking in a garden, wind moving her hair, hazy afternoon sun",
    "A young woman in a sports top speaking after exercise, gym behind her, cool overhead light",
    "A man in a wool hat speaking outdoors at dusk, streetlight coming on behind him",
    "A woman in a paint-stained shirt speaking in a studio, canvases behind, north-facing skylight",
    "A man in a collarless shirt speaking with his hands clasped, softly lit interior, shallow focus",
    "A woman with a pixie cut speaking energetically, colourful mural behind her, bright daylight",
    "A man in a heavy coat speaking on a bridge, river and grey sky behind him",
    "A woman seated cross-legged on a floor cushion talking to the camera, low warm light",
    "A man in a bow tie speaking with precise gestures, wood-panelled room, warm lamps",
    "A woman in a raincoat speaking under an umbrella, rain visible, muted grey daylight",
    "A young man in a football shirt speaking excitedly, garden fence behind him, evening sun",
    "A woman in a velvet jacket speaking under stage lighting, dark auditorium behind",
    "A man with grey stubble speaking quietly by a window, rain running down the glass",
    "A woman in a cycling jersey speaking while holding a helmet, roadside, bright morning",
    "A man in a fisherman's jumper speaking on a harbour wall, boats out of focus behind",
    "A woman in a graduation gown speaking to the camera and smiling, stone building behind",
    "A man in a dressing gown speaking with a mug in hand, morning kitchen, low sun",
    "A woman in a fitted blazer speaking in front of a bookcase, warm practical lamps",
    "A man in a hi-vis vest speaking on a building site, cranes out of focus, hard daylight",
    "A woman with silver earrings speaking closely to the camera, deep shadow on one side",
    "A man in a cricket jumper speaking on a lawn, long shadows, late golden light",
    "A woman in a hijab speaking calmly to the camera, soft window light, neutral interior",
    "A man in a beanie speaking in a stairwell, cool fluorescent light overhead",
]

# Trades and craft. Continuous, repetitive, hand-scale motion with a fixed
# subject -- close to ideal for a sliding-window model, and almost absent from
# the original bank.
TRADES = [
    "A blacksmith hammering glowing metal on an anvil, sparks scattering, dark forge",
    "A glassblower turning a gather of molten glass, furnace glow on their face",
    "A cobbler stitching the welt of a leather shoe, work lamp, cluttered bench",
    "A watchmaker fitting a tiny gear with tweezers, loupe in one eye, bright task light",
    "A tailor pinning fabric on a dress form, chalk marks, daylight through a tall window",
    "A weaver passing a shuttle through a loom, coloured threads, warm workshop light",
    "A luthier planing the top of a guitar body, curls of wood falling, window light",
    "A bookbinder pressing a spine in a clamp, glue brush at hand, soft overhead light",
    "A calligrapher drawing a long stroke with a broad nib, ink pooling, desk lamp",
    "A printmaker rolling ink across a plate, hand press behind, bright studio",
    "A stonemason chiselling a block of limestone, dust in the air, open yard light",
    "A cooper hammering a hoop onto a barrel, wood shavings underfoot, dim workshop",
    "A farrier shaping a horseshoe over a small anvil, stable doorway light behind",
    "A sign painter drawing a gold letter with a fine brush, glass shopfront, street light behind",
    "A neon bender heating a glass tube over a flame, dark workshop, orange glow",
    "A ceramicist trimming a leather-hard bowl on a wheel, clay ribbons curling away",
    "A jeweller soldering a ring with a small torch, bright pinpoint flame, dark bench",
    "A leatherworker burnishing an edge with a wooden tool, warm bench lamp",
    "A knife sharpener drawing a blade across a wet stone, steady rhythm, window light",
    "An upholsterer stretching fabric over a chair frame and tacking it down, workshop light",
    "A cabinetmaker cutting a dovetail with a fine saw, sawdust, clear north light",
    "A basket weaver bending willow into a rim, hands working steadily, shaded porch",
    "A candlemaker dipping wicks into wax, slow repeated motion, dim warm room",
    "A cheesemaker turning a wheel on a wooden shelf, cool cellar light",
    "A brewer stirring a mash tun with a long paddle, steam rising, industrial lighting",
    "A cooper's apprentice sanding a stave, focused, dust catching a shaft of sunlight",
    "A tattoo artist working on a forearm, gloved hands, bright directional lamp",
    "A barber trimming a beard with clippers, mirror behind, warm barbershop light",
    "A florist wiring a stem into an arrangement, cool shop light, buckets of flowers",
    "A milliner shaping felt over a wooden hat block with steam, dim workroom",
    "A glazier scoring a sheet of glass and snapping it cleanly, workshop daylight",
    "A locksmith cutting a key on a machine, sparks and metal dust, harsh work light",
    "A saddler stitching leather with two needles, saddle clamped upright, warm light",
    "A restorer cleaning varnish from an oil painting with a swab, raking light",
    "A model maker gluing a tiny part with tweezers, magnifier lamp, dark room",
    "A clockmaker winding a movement and listening to it, quiet workshop, side light",
    "A stained-glass artist leading a panel together, coloured light falling on the bench",
    "A woodturner shaping a bowl on a lathe, shavings flying, focused work light",
    "A shoemaker hammering a heel into place, last held between the knees, dim shop",
    "An engraver cutting a line into a copper plate with a burin, bright angled lamp",
    "A bell founder scraping a mould surface smooth, dusty foundry, high windows",
    "A thatcher combing reed into place on a roof, bright overcast sky behind",
    "A sailmaker feeding heavy canvas through an industrial machine, loft daylight",
    "A wheelwright fitting a spoke into a wooden hub, open workshop door, bright outside",
    "A gunsmith checkering a walnut stock with a fine file, bench lamp, dark room",
    "A potter centring a lump of clay, wet hands, slip running, warm studio",
    "A silversmith planishing a bowl with a small hammer, rhythmic ringing, dim bench",
    "A bowyer scraping the belly of a longbow, long even strokes, window light",
    "A glass engraver working a wheel against a goblet, water dripping, bright lamp",
    "A tanner working oil into a hide with a cloth, dim tannery, high dusty light",
    "A parchment maker scraping a stretched skin with a curved blade, cool daylight",
    "A mosaic artist setting tesserae into wet mortar, bright overhead studio light",
    "A gilder laying gold leaf onto a frame with a brush, still air, warm lamp",
    "A blacksmith quenching a hot blade in oil, steam and flame flaring briefly",
    "A carpenter marking a mortise with a gauge, pencil behind the ear, soft daylight",
    "A pipe organ builder voicing a metal pipe, quiet church interior, tall windows",
    "A rope maker twisting strands on a walk, long perspective, flat afternoon light",
    "A knife maker grinding a bevel on a belt sander, sparks streaming, dark shop",
    "A puppet maker articulating a wooden joint, tools on the bench, warm lamp",
    "A book conservator flattening a page under weights, gloves, cool even light",
    "A brass polisher buffing a lamp on a wheel, cloth blur, dim workshop",
    "A dyer lifting fabric from an indigo vat, deep blue dripping, shaded courtyard",
    "A furniture restorer rubbing wax into a tabletop, circular motion, warm light",
    "A lens grinder polishing an optic on a spinning pad, water film, bright bench",
    "A hat blocker brushing a felt brim, steam kettle beside, dim workroom",
    "A screen printer pulling a squeegee across a screen, bright even studio light",
    "A cobbler's wheel spinning as a sole is trimmed, dust and leather smell implied",
    "A bronze caster pouring molten metal into a mould, intense orange glow, dark foundry",
    "A chair caner threading rush through a seat frame, patient hands, porch light",
    "A stone carver dusting chips from a half-finished relief, raking sunlight",
]

# Food preparation. Hands, steam, liquids and repetitive motion at a fixed
# camera -- and a very different texture and colour statistic from the studio
# talking heads above.
KITCHEN = [
    "A cook folding an omelette in a pan, gas flame beneath, warm kitchen light",
    "A baker scoring a loaf before it goes into the oven, flour on the crust, morning light",
    "A chef julienning carrots quickly and evenly, steel bench, bright overhead light",
    "A pastry chef piping cream onto a tart, steady hands, cool even light",
    "A cook tossing vegetables in a wok over a high flame, steam and smoke rising",
    "A barista pouring a rosetta into a flat white, close framing, cafe window light",
    "A person kneading pasta dough and folding it over, wooden board, soft daylight",
    "A chef spooning sauce around a plate, tweezers at hand, dark restaurant pass",
    "A cook cracking eggs into a bowl one after another, marble counter, bright light",
    "A person rolling sushi on a bamboo mat, precise movements, cool clean light",
    "A baker dusting a tray of pastries with icing sugar, warm bakery light",
    "A chef searing a steak, smoke rising, flames occasionally licking up",
    "A person stirring risotto slowly in a wide pan, steam, evening kitchen light",
    "A cook grating cheese over a bowl of pasta, warm domestic light",
    "A pastry chef tempering chocolate on a marble slab, spatula sweeping, cool light",
    "A person pressing tortillas and laying them on a hot griddle, steam rising",
    "A chef deboning a fish with a thin blade, clean stainless surface, bright light",
    "A cook ladling soup into a bowl, steam curling up, warm evening light",
    "A person peeling apples in one long ribbon, kitchen table, window light",
    "A baker shaping baguettes on a floured bench, rhythmic, early morning light",
    "A cook flipping pancakes on a griddle, batter bubbling, bright kitchen",
    "A person whisking egg whites in a copper bowl, steady circular motion, soft light",
    "A chef torching the top of a creme brulee, flame passing over sugar, dark counter",
    "A cook pulling noodles by hand, stretching and folding, flour dust, bright light",
    "A person pouring batter into a hot waffle iron, steam escaping the seam",
    "A chef arranging thin slices of fish on a plate, tweezers, focused task light",
    "A cook stirring a large pot of stew with a wooden spoon, steam, warm light",
    "A person icing a cake with a palette knife, turntable rotating slowly, soft light",
    "A tea master pouring hot water over leaves in a small pot, steam, quiet dim room",
    "A cook shucking oysters on ice, knife twisting, cold blue-tinted light",
    "A person rolling dumplings and pleating the edges, board of flour, bright light",
    "A chef straining pasta into a colander, steam billowing up, kitchen light",
    "A person grinding spices in a mortar and pestle, steady rhythm, warm light",
    "A cook basting a roast with a spoon, oven door open, warm interior glow",
    "A bartender stirring a drink in a mixing glass, ice ringing, dim bar light",
    "A person pouring olive oil in a thin stream over a salad, bright daylight",
    "A cook flipping a crepe in a wide pan, quick wrist motion, warm kitchen",
    "A person spooning yoghurt into a bowl and adding berries, morning window light",
    "A chef plating a dessert with a quenelle of ice cream, cold plate, dark background",
    "A person pouring coffee from a stovetop pot into a small cup, morning light",
]

# Music and performance. Continuous articulated motion, strong rhythmic
# structure, and a wide range of lighting from dark stages to bright rehearsal
# rooms.
MUSIC = [
    "A cellist drawing a long bow stroke, eyes closed, warm rehearsal room light",
    "A drummer playing a steady groove, sticks blurring, dim practice space",
    "A pianist's hands moving across the keys, close framing, single warm lamp",
    "A saxophonist playing under a single spotlight, smoke in the beam, dark club",
    "A singer holding a long note at a microphone, eyes shut, deep red stage light",
    "A guitarist bending a string on an electric guitar, amp glowing behind, dark stage",
    "A harpist plucking with both hands, gilded frame catching warm light",
    "A flautist playing in a bright rehearsal room, music stand, tall windows",
    "A double bass player walking a line, upright instrument, dim jazz club",
    "A violinist tuning and then beginning to play, warm practice room light",
    "A DJ moving a fader and nodding to the beat, coloured lights sweeping behind",
    "A conductor raising both hands and cueing an entry, dark hall, focused light",
    "An accordionist playing on a stone step, warm late afternoon sun",
    "A banjo player picking quickly on a wooden porch, bright overcast light",
    "A trumpeter emptying a valve and lifting the horn to play, dim stage",
    "A choir singer holding a folder and singing, stained glass light behind",
    "A tabla player's hands moving rapidly on the drums, warm floor lamp",
    "A koto player plucking strings, seated on a mat, soft diffuse daylight",
    "A church organist's feet moving on the pedalboard, dim gallery light",
    "A busker playing a fiddle in an underpass, hard directional light, tiled walls",
    "A harmonica player cupping the instrument, eyes closed, warm bar light",
    "A bagpiper playing on a windy hillside, tartan moving, grey daylight",
    "A marimba player's mallets moving across the bars, bright rehearsal light",
    "A sitar player sitting cross-legged, hands on the frets, dim warm room",
    "A synth player adjusting a knob while a pad sustains, blue and purple glow",
    "A bass guitarist locked in with the drums, stage haze, moving lights",
    "A ballet dancer rising onto pointe and holding it, mirrored studio, cool light",
    "A tap dancer's shoes striking a wooden floor, sharp rhythm, warm stage light",
    "A flamenco dancer turning with a fan, red dress, dark stage, hard side light",
    "A contemporary dancer rolling slowly across a floor, bare studio, north light",
    "A puppeteer working a marionette on a small stage, warm footlights",
    "A magician turning a coin over their knuckles, close framing, dark background",
    "A mime moving slowly against an invisible wall, plain backdrop, flat light",
    "A juggler keeping three clubs moving, park behind, golden hour light",
    "A circus aerialist turning slowly on a hoop, dark tent, single beam",
    "An actor delivering a monologue on a bare stage, single overhead light",
    "A stand-up comic gesturing at a microphone, brick wall behind, warm spot",
    "A street performer painting themselves still as a statue, bright square daylight",
    "A beatboxer close to a microphone, hand cupped, dark room, rim light",
    "A ukulele player strumming on a beach at sunset, warm backlight",
]

# Sport and physical movement. Fast, whole-body motion with a stable frame --
# the opposite end of the motion-magnitude axis from the talking heads.
SPORT = [
    "A swimmer doing front crawl in a pool lane, underwater view, shafts of light",
    "A boxer working a speed bag, rhythmic blur, dusty gym light",
    "A climber reaching for a hold on an indoor wall, chalk dust, bright colour",
    "A runner on a track rounding a bend, morning light, long shadows",
    "A rower pulling on an indoor machine, steady breathing, cool gym light",
    "A skateboarder rolling slowly across an empty park bowl, late afternoon sun",
    "A tennis player serving, ball toss at the top of frame, bright daylight",
    "A footballer juggling a ball on their instep, grass pitch, evening light",
    "A weightlifter setting up over a barbell and taking a breath, harsh gym light",
    "A gymnast holding a handstand on a beam, quiet hall, high windows",
    "A yoga teacher moving slowly into a low lunge, warm studio, wooden floor",
    "A cyclist climbing out of the saddle on a hill road, low sun behind",
    "A kayaker paddling across flat water at dawn, mist on the surface",
    "A surfer paddling out through a small wave, bright morning glare",
    "A skier carving through soft snow, spray rising, blue shadows",
    "A snowboarder traversing slowly across a slope, overcast flat light",
    "A fencer lunging and recovering, white kit, cool hall lighting",
    "A judo practitioner gripping a partner's jacket and shifting weight, dojo light",
    "An archer drawing a bow and holding the anchor, field behind, soft daylight",
    "A basketball player shooting free throws alone, empty gym, high windows",
    "A dancer skipping rope quickly, dust on the floor, single hanging bulb",
    "A martial artist practising a slow form in a park at sunrise, mist",
    "A horse and rider cantering along a beach, spray from the hooves, low sun",
    "A rock climber on a sea cliff reaching up, sea moving far below, bright light",
    "A hiker stepping up onto a rock and pausing, wide valley behind, hazy light",
    "A pole vaulter running in with the pole, stadium, bright floodlights",
    "A table tennis player rallying, fast bat movement, flat indoor light",
    "A golfer swinging through and holding the finish, fairway, low golden light",
    "A rugby player passing along the line, wet grass, floodlit evening",
    "A goalkeeper diving to save a low shot, spray of turf, bright daylight",
    "A sprinter setting into blocks and breathing out, stadium, warm evening light",
    "A cricketer bowling in from the crease, dusty pitch, hard midday sun",
    "A diver walking to the end of a board and pausing, still pool below",
    "A parkour athlete stepping along a low wall, quiet street, morning light",
    "A wheelchair racer pushing along a track, hands blurring, bright daylight",
    "A person on a climbing treadmill, steady hand movement, dim gym",
    "An ice skater gliding across an outdoor rink, string lights above, dusk",
    "A speed skater in a low crouch on a long oval, cool indoor light",
    "A trail runner descending a rocky path, dust rising, dappled forest light",
    "A stand-up paddleboarder crossing a still lake at dawn, reflections",
]

# Work, study and screens. Small motion against a fixed subject, and the screen
# glow gives a light source the rest of the bank does not have.
WORK = [
    "A programmer typing quickly, code reflected in their glasses, dark room",
    "An architect drawing on a large sheet with a scale rule, drafting lamp",
    "An editor scrubbing through footage on a timeline, dual monitors, dim suite",
    "An accountant turning pages of a ledger and marking a figure, desk lamp",
    "A translator speaking into a headset in a booth, small light on the desk",
    "A radio host adjusting a microphone arm and leaning in, dim studio, red light",
    "An air traffic controller watching a screen and speaking, dark room, green glow",
    "A watch repairer's hands under a magnifier, bright ring light",
    "A designer sketching on a tablet with a stylus, bright screen, dark surround",
    "A student highlighting a textbook at a library desk, green banker's lamp",
    "A teacher marking papers at a kitchen table late at night, single lamp",
    "A cartographer tracing a coastline on a large map, bright even light",
    "A stenographer's hands moving on a small keyboard, courtroom, flat light",
    "A tailor's assistant measuring a sleeve and noting it down, shop daylight",
    "A curator adjusting the angle of a small object in a display case, gallery light",
    "A sound engineer moving faders on a large console, meters flickering, dim room",
    "A photographer reviewing frames on a camera back, studio strobes behind",
    "A pilot running through a checklist in a cockpit, instrument glow, dusk outside",
    "A ship's officer plotting a course on a chart table, red night lighting",
    "A dispatcher speaking into a headset, wall of screens behind, cool light",
    "A journalist typing on a laptop in a hotel room, window light, city outside",
    "A clerk stamping documents one after another, post office, flat overhead light",
    "A biologist labelling sample tubes in a rack, cold laboratory light",
    "A weather forecaster gesturing at a map, studio lighting, blue backdrop",
    "A pharmacist counting tablets into a tray, bright counter light",
    "A bank teller counting notes through a machine, quiet interior, even light",
    "A barista's colleague writing the specials on a chalkboard, morning shop light",
    "A tattoo shop receptionist flipping through an appointment book, warm lamp",
    "A watch dealer examining a dial with a loupe, dark velvet tray, bright spot",
    "An auctioneer taking bids and gesturing, warm room light, wood panelling",
    "A locksmith at a van workbench cutting a key, roadside, overcast light",
    "A gardener at a potting bench filling trays with compost, greenhouse light",
    "A vet writing notes after an examination, clinic, cool ceiling light",
    "A driving instructor pointing at the road ahead from the passenger seat, daylight",
    "A projectionist threading film through a projector, dim booth, warm lamp",
    "A bookseller shelving new stock and straightening spines, warm shop light",
    "A museum conservator brushing dust from a fossil, bright angled lamp",
    "A drone pilot watching a controller screen in a field, bright overcast sky",
    "A seamstress feeding fabric through an industrial machine, task light",
    "A call centre worker adjusting a headset and smiling while speaking, flat light",
]

# Outdoors and travel. Wide scenes with a person in them, moving daylight and
# weather -- deliberately the hardest lighting in the bank.
OUTDOOR = [
    "A hiker adjusting the straps of a rucksack on a ridge, wind, bright hazy light",
    "A woman standing at the edge of a cliff looking out to sea, wind in her coat",
    "A man rowing a small wooden boat across a still lake at dawn",
    "A traveller waiting on a rural platform with a suitcase, low winter sun",
    "A cyclist stopping to drink from a bottle on a country lane, dappled shade",
    "A shepherd walking behind a flock along a stone-walled track, grey light",
    "A woman reading on a picnic blanket, grass moving in the wind, bright afternoon",
    "A man skimming a stone across flat water, ripples spreading, evening light",
    "A woman photographing a mountain range from a viewpoint, cold clear light",
    "A man chopping firewood outside a cabin, breath visible, low winter sun",
    "A woman pitching a tent in a meadow, fabric catching the wind, golden hour",
    "A man fishing from a riverbank, line casting out, mist on the water",
    "A woman walking a coastal path with a dog, sea and sky behind, bright wind",
    "A man refilling a water bottle from a mountain stream, cold clear light",
    "A woman feeding chickens in a farmyard, morning light through a gate",
    "A man on a ladder picking apples into a canvas bag, orchard, soft autumn light",
    "A woman digging in an allotment bed, spade turning soil, flat overcast light",
    "A man loading hay bales onto a trailer, dust in the air, hard summer sun",
    "A woman leading a horse out of a stable, warm doorway light behind",
    "A man scraping ice from a windscreen, breath visible, blue pre-dawn light",
    "A woman shovelling snow from a path, steady rhythm, grey winter light",
    "A man sitting on a rock eating a sandwich, wide valley behind, hazy light",
    "A woman crossing a wooden footbridge over a stream, dappled forest light",
    "A man launching a kayak from a shingle beach, small waves, overcast",
    "A woman in waders casting a fly line, river bend, low golden light",
    "A man tending a beehive in a veil and gloves, smoke drifting, bright meadow",
    "A woman sketching a landscape in a small notebook, wind moving the pages",
    "A man walking along a railway embankment at dusk, long shadows",
    "A woman sitting on a harbour wall watching boats, gulls overhead, bright grey",
    "A man tying a boat to a mooring ring, water slapping the stone, soft light",
    "A woman running along a beach at low tide, wet sand reflecting the sky",
    "A man setting up a telescope in a field at dusk, first stars appearing",
    "A woman collecting shells at the tideline, low sun behind her",
    "A man walking through tall reeds at the edge of a marsh, warm evening light",
    "A woman climbing a stile in a hedgerow, sheep field beyond, bright overcast",
    "A man carrying a canoe on his shoulders down to the water, dappled shade",
    "A woman stopping to look at a map at a trail junction, forest light",
    "A man raking leaves into a pile in a garden, autumn light, low sun",
    "A woman hanging washing on a line, sheets moving in the wind, bright day",
    "A man watering a vegetable garden with a can, evening light, long shadows",
]

# Quiet domestic interiors. Small motion, warm practical light, and the
# strongest test of whether identity and fine detail hold over a long rollout.
DOMESTIC = [
    "A woman folding laundry on a bed, slow steady motion, afternoon window light",
    "A man ironing a shirt, steam rising, kitchen light behind him",
    "A woman watering houseplants on a windowsill, low sun through the leaves",
    "A man tuning a radio dial, warm lamp, evening living room",
    "A woman brushing her hair in front of a window, soft morning light",
    "A man lighting a fire in a wood stove, flames catching, dim room",
    "A woman writing a letter at a desk, fountain pen, single lamp, night",
    "A man polishing shoes on a newspaper, circular motion, kitchen light",
    "A woman sorting through a box of old photographs, warm attic light",
    "A man making a bed, sheet billowing and settling, bright bedroom",
    "A woman doing a jigsaw puzzle at a table, pieces fitting, lamp light",
    "A man winding a mantel clock, quiet room, afternoon light",
    "A woman painting her nails at a small table, focused, window light",
    "A man sharpening a pencil with a small knife, shavings falling, desk lamp",
    "A woman kneading dough at a kitchen table, flour dust in the light",
    "A man repotting a plant, soil spilling onto newspaper, bright kitchen",
    "A woman lighting candles on a table one by one, room darkening around",
    "A man sewing a button onto a coat, thread pulled through, lamp light",
    "A woman stacking books onto a shelf, dust motes in a sunbeam",
    "A man cleaning a camera lens with a cloth, careful movements, window light",
    "A woman drinking tea and watching rain on the window, muted grey light",
    "A man cutting flowers and putting them in a jar, bright kitchen counter",
    "A woman rocking slowly in a chair with a blanket, firelight on her face",
    "A man scrolling through records in a crate, warm shop-like room light",
    "A woman plaiting her own hair in front of a mirror, morning bathroom light",
    "A man wiping down a kitchen counter, steady sweeps, evening light",
    "A woman putting on earrings in front of a mirror, warm bulbs around the frame",
    "A man setting a table, placing cutlery one piece at a time, low sun",
    "A woman stretching on a mat in a living room, morning light on the floor",
    "A man feeding a cat from a tin, cat winding around his legs, kitchen light",
    "A woman opening curtains and light flooding into a room",
    "A man carrying a mug through a hallway, warm light spilling from a doorway",
    "A woman folding paper into a small shape, precise hands, desk lamp",
    "A man restringing a guitar, winding the tuner, warm living room light",
    "A woman shelling peas into a bowl, steady rhythm, kitchen window light",
    "A man dusting a bookshelf with a cloth, sunbeam full of motes",
    "A woman knitting while watching something off camera, lamp beside her",
    "A man buttoning a coat by the front door, hallway light, about to leave",
    "A woman putting a record on a turntable and lowering the needle, warm light",
    "A man drying dishes and stacking them, window over the sink, evening light",
]

# Clinical, scientific and ceremonial. Cool and neutral lighting, and content
# types with almost no representation in the original bank.
INSTITUTIONAL = [
    "A surgeon tying a suture knot, gloved hands, bright overhead theatre light",
    "A nurse taking a blood pressure reading, cuff inflating, clinic light",
    "A dentist examining with a small mirror, bright chair lamp, blue gloves",
    "A physiotherapist guiding a shoulder through a slow range of motion",
    "A radiographer positioning a patient's arm, cool scanner room light",
    "A paramedic checking a monitor in the back of an ambulance, harsh strip light",
    "A researcher pipetting into a row of wells, bright bench light, blue gloves",
    "A chemist swirling a flask over a stirrer, coloured solution, fume hood light",
    "A microscopist adjusting focus and looking up, dim room, illuminated stage",
    "An astronomer adjusting a telescope mount in a dome, red safety light",
    "A geologist splitting a rock with a hammer and examining the face, field light",
    "A marine biologist lifting a sample net onto a deck, bright sea glare",
    "An archaeologist brushing soil from a fragment in a trench, hard sun",
    "A vet listening to a dog's chest with a stethoscope, calm clinic light",
    "A lab technician loading a centrifuge and closing the lid, cool light",
    "An engineer testing a circuit board with a probe, bench lamp, dark room",
    "A metrologist reading a dial gauge on a granite table, clean bright light",
    "A wind tunnel technician adjusting a model, cavernous space, work lights",
    "A librarian scanning a barcode and stamping a date, quiet counter light",
    "A judge writing a note at the bench, wood panelling, warm formal light",
    "A priest lighting altar candles, tall stained glass windows behind",
    "A monk sweeping a courtyard slowly, early light on stone",
    "A bride adjusting a veil in front of a tall mirror, soft daylight",
    "A tea ceremony host whisking matcha in a bowl, tatami room, diffuse light",
    "A calligrapher preparing ink on a stone before writing, quiet dim room",
    "A flag bearer holding a pole steady in the wind, bright overcast sky",
    "A choir conductor lowering their hands at the end of a phrase, church light",
    "A glassblower's assistant opening a furnace door, intense orange light spilling",
    "A miner adjusting a headlamp underground, dust in the beam, black surround",
    "A lighthouse keeper climbing a spiral stair, small windows, cold daylight",
]

# Older adults. Motion statistics, pacing and skin/hair detail that the rest of
# the bank does not cover.
#
# NOTE: this bank contains no minors, by request. Nothing here depicts or
# implies anyone under 18. See `assert_no_minors()` at the bottom of this file,
# which enforces it as a test rather than a convention.
ELDERS = [
    "An older woman tending roses with secateurs, sunhat, bright garden light",
    "An older man doing a crossword with a pen, reading glasses, lamp light",
    "An elderly couple walking arm in arm down a lane, autumn trees, low sun",
    "An older woman playing an upright piano from memory, warm parlour light",
    "An older man feeding pigeons from a bench, city square, flat daylight",
    "An elderly woman threading a needle carefully, bright window light",
    "An older man polishing a vintage car bonnet, garage, hard work light",
    "An elderly woman arranging photographs in an album, warm table lamp",
    "An older man tying fishing flies at a bench, magnifier, focused lamp",
    "An elderly woman watering a windowbox, morning light on the street below",
    "An older man kneading bread dough slowly on a scrubbed table, morning light",
    "An elderly woman winding wool into a ball from a skein, lamp beside her",
    "An older man walking a dog slowly along a canal path, low autumn sun",
    "An elderly woman pruning a bonsai with small shears, bright bench light",
    "An older man carving a walking stick handle with a knife, porch light",
    "An elderly woman practising scales on a violin, warm sitting room",
    "An older man cleaning a pair of spectacles with a cloth, window light",
    "An elderly woman stirring jam in a wide pan, steam rising, kitchen light",
    "An older man setting up a chessboard piece by piece, warm lamp",
    "An elderly woman doing slow tai chi in a park at dawn, mist on the grass",
]

PEOPLE_EXT = (TALKING + TRADES + KITCHEN + MUSIC + SPORT + WORK + OUTDOOR
              + DOMESTIC + INSTITUTIONAL + ELDERS)

# -------------------------------------------------------------------- animals
ANIMALS_EXT = [
    "A snow leopard picking its way along a rocky ledge, cold overcast light",
    "A grey wolf trotting across a frozen lake, low winter sun behind",
    "A brown bear turning over a rock in a shallow river, bright forest light",
    "A lynx sitting still in deep snow, ears twitching, flat grey light",
    "A stag standing in bracken and lifting its head, autumn morning mist",
    "A herd of bison moving slowly through long grass, dust and low sun",
    "A giraffe reaching up to strip leaves from a thorn tree, hard midday light",
    "A zebra flicking its tail in dry grass, heat haze, bright savannah",
    "A hippopotamus surfacing slowly in a muddy river, ears flicking water",
    "A rhinoceros walking through dust at sunset, long shadows behind",
    "A cheetah scanning the plain from a low mound, wind in the grass",
    "A lioness lying in shade and yawning, dappled acacia light",
    "A meerkat standing upright on a mound, alert, bright desert light",
    "A sloth moving one arm slowly along a branch, humid green light",
    "An orangutan swinging slowly between branches, dappled canopy light",
    "A gorilla sitting and chewing a stem, deep forest shade",
    "A lemur sunning itself on a branch, arms out, bright morning light",
    "A red panda walking along a mossy log, soft overcast forest light",
    "A koala shifting position in a eucalyptus fork, hazy blue-grey light",
    "A kangaroo grazing then lifting its head, dry paddock, low golden sun",
    "An otter rolling onto its back in a river, water beading on fur",
    "A beaver swimming across a still pond at dusk, wake spreading behind",
    "A badger emerging from a sett at twilight, low blue light",
    "A hedgehog moving through leaf litter, torchlit, dark surround",
    "A squirrel turning a nut over in its paws on a branch, autumn light",
    "A hare sitting motionless in a ploughed field, low morning sun",
    "A mole hill of soil shifting as something moves beneath, bright lawn",
    "A field mouse climbing a grass stem, shallow focus, warm meadow light",
    "A bat hanging and stretching one wing, dim cave light",
    "A porcupine walking slowly across pine needles, dappled forest light",
    "A raccoon washing something in shallow water, night, cool moonlight",
    "A skunk foraging along a fence line at dusk, low warm light",
    "A wild boar rooting in mud in a dark wood, shafts of light",
    "A mountain goat standing on a narrow ledge, bright alpine light",
    "An ibex silhouetted on a ridge at sunset, warm rim light",
    "A camel walking across dunes, long shadow, hard low sun",
    "A llama chewing and looking toward the camera, high altitude clear light",
    "An alpaca in a misty field at dawn, breath visible",
    "A donkey shaking its head in a dusty paddock, bright afternoon",
    "A cow chewing cud in a barn doorway, bright light outside, dark within",
    "A calf standing up unsteadily in straw, warm barn light",
    "A pig rooting in mud in a farmyard, flat overcast light",
    "A goat balancing on a fallen tree trunk, dappled woodland light",
    "A ram standing in heather on a hillside, wind, grey light",
    "A sheepdog lying alert with its head on its paws, warm kitchen light",
    "A border collie crouching low and watching sheep, bright field",
    "A labrador shaking water from its coat after a swim, spray flying",
    "A beagle following a scent along a hedgerow, nose down, soft light",
    "A greyhound running flat out across a field, motion blur behind",
    "A terrier digging enthusiastically in sand, bright beach light",
    "A husky pulling on a harness in snow, breath steaming, blue shadows",
    "A dachshund trotting along a pavement, low camera, warm evening light",
    "A pug asleep on a sofa and twitching, warm lamp light",
    "A great dane standing and stretching, tall against a doorway, hall light",
    "A dog shaking itself dry in slow motion, droplets flying, bright light",
    "A puppy sniffing at a flower in a garden, soft morning light",
    "A siamese cat stalking slowly across a wooden floor, low sun",
    "A maine coon cat grooming its tail, warm window light",
    "A cat leaping onto a windowsill and settling, afternoon light",
    "A cat's paw batting at a water surface in a bowl, ripples, kitchen light",
    "A cat sleeping curled in a patch of sun, slow breathing",
    "A cat watching birds through glass, tail twitching, bright window",
    "A rabbit washing its face with both paws, hutch straw, soft light",
    "A guinea pig eating a piece of vegetable, warm indoor light",
    "A ferret exploring along a shelf, quick movements, dim room",
    "A hamster running in a wheel, warm cage light, dark surround",
    "A horse tossing its mane in a paddock, dust and low sun",
    "A foal running alongside a mare in a field, bright morning",
    "A horse drinking from a trough, ripples, hard midday light",
    "A shire horse pulling a cart along a lane, dust, warm afternoon",
    "An eagle perched on a crag, feathers ruffling in the wind, cold light",
    "A kestrel hovering over a field, wings adjusting, bright overcast",
    "A barn owl flying slowly along a hedge at dusk, pale against dark",
    "A heron standing motionless in shallow water then striking, grey light",
    "A kingfisher perched on a reed above a stream, bright dappled light",
    "A robin hopping along a fence rail, cold winter light",
    "A blackbird pulling a worm from a lawn, bright overcast",
    "A swan gliding across still water, reflection perfect beneath",
    "A duck landing on a pond, feet skimming the surface, spray",
    "A goose stretching its wings on a riverbank, morning mist",
    "A pelican folding its wings after landing on a post, bright coastal light",
    "A puffin standing on a cliff edge, wind ruffling, grey sea behind",
    "A penguin waddling across ice then sliding onto its belly, flat white light",
    "A flamingo standing on one leg and preening, shallow pink water",
    "A peacock slowly raising its tail, iridescent, bright garden light",
    "A rooster crowing on a fence post, early morning light",
    "A hen scratching in a dust bath, bright farmyard",
    "A pigeon strutting along a window ledge, city light behind",
    "A crow examining something on tarmac, overcast urban light",
    "A magpie hopping across a lawn, bright morning",
    "A woodpecker drumming on a trunk, dappled forest light",
    "A swallow perched on a wire, wind ruffling, bright sky behind",
    "A stork standing in a nest on a chimney, warm evening light",
    "A hummingbird feeding at a feeder, wings a blur, bright garden",
    "A parrot cracking a seed in its beak, tropical shade",
    "A budgerigar preening on a perch, warm indoor light",
    "A canary hopping between perches, bright window light",
    "A seagull hovering into the wind above a harbour, grey bright sky",
    "A tern diving toward the sea and pulling up, bright glare",
    "A turtle swimming slowly over a reef, sunlight rippling on its shell",
    "A sea turtle surfacing to breathe, calm water, bright light",
    "A shoal of sardines turning as one, shafts of light through blue water",
    "A manta ray gliding past, silhouetted against the surface",
    "A reef shark cruising along a drop-off, deep blue water",
    "A clownfish moving among anemone tentacles, bright reef light",
    "A seahorse gripping a strand of weed, gentle current, soft light",
    "An octopus changing colour across a rock, shallow clear water",
    "A cuttlefish hovering and rippling its fins, dim blue water",
    "A jellyfish pulsing slowly in dark water, translucent, single beam",
    "A starfish moving imperceptibly across a rock pool, bright shallow water",
    "A crab scuttling sideways across wet sand, low sun",
    "A lobster backing into a crevice, dim underwater light",
    "A seal hauling itself onto a rock, spray, bright coastal light",
    "A sea lion turning underwater in a shaft of sunlight",
    "A whale's tail lifting and sliding under the surface, grey sea",
    "A dolphin leaping clear of the water, spray catching the sun",
    "A frog inflating its throat on a lily pad, warm pond light",
    "A tree frog gripping a wet leaf, rain dripping, green light",
    "A newt swimming through pondweed, dappled shallow light",
    "A chameleon moving one foot at a time along a branch, bright foliage",
    "A gecko clinging to a wall and blinking, warm lamp light",
    "A snake moving slowly across warm sand, low sun, long shadow",
    "A python coiled and slowly shifting, dim terrarium light",
    "An iguana basking on a rock, bright tropical sun",
    "A tortoise walking slowly across grass, bright afternoon",
    "A crocodile lying motionless with one eye open, muddy bank, hard light",
    "A monarch butterfly opening and closing its wings on a flower, bright sun",
    "A dragonfly hovering over water then darting away, bright reflections",
    "A praying mantis turning its head, shallow focus, warm light",
    "A spider repairing a web strand by strand, backlit dew",
    "A snail moving along a wet leaf, slow trail, grey light",
    "A colony of ants carrying leaf pieces along a branch, dappled light",
    "A beetle climbing a grass stem, bright meadow, shallow depth of field",
    "A moth resting on a lit window at night, wings still",
]

# --------------------------------------------------------------------- nature
NATURE_EXT = [
    "A glacier calving slowly into a fjord, ice falling, flat grey light",
    "Meltwater running in channels across blue glacier ice, bright midday sun",
    "An iceberg drifting in still black water, pale under an overcast sky",
    "Frost forming on a window pane, crystals spreading, cold dawn light",
    "Icicles dripping steadily from a roof edge, bright winter sun",
    "A frozen waterfall with water still running behind the ice, blue shade",
    "Snow sliding off a pine branch in a clump, quiet forest",
    "A blizzard blowing across an empty road, headlights faint, grey light",
    "Wind-blown snow streaming off a mountain ridge, hard alpine light",
    "A thaw stream cutting through old snow, bright spring light",
    "Steam rising from a hot spring into cold air, blue morning light",
    "A geyser building and then erupting, spray drifting, bright sky",
    "Bubbling mud in a geothermal pool, sulphurous steam, flat light",
    "Lava crusting over and cracking bright orange, dark night",
    "Ash drifting from a volcanic vent, grey daylight, stark ground",
    "Black sand beach with waves washing over it, high contrast light",
    "A desert dune ridge with sand streaming off the crest, low sun",
    "Heat shimmer over a salt flat, hard white light, distant mountains",
    "A dust devil moving across dry ground, bright afternoon",
    "A cactus standing against a deep blue desert sky, hard shadows",
    "Rain falling on parched earth, dust puffing up, grey storm light",
    "A flash flood running down a dry wash, muddy water, overcast",
    "A canyon river seen from above, slow green water, deep shade",
    "Sandstone walls glowing with reflected light in a slot canyon",
    "A mesa at sunrise with mist in the valley below, warm light",
    "Rolling fog spilling over a coastal ridge, late afternoon sun",
    "A cloud inversion filling a valley at dawn, peaks above it",
    "Cumulus clouds building over a plain, shadows moving across fields",
    "A thunderstorm anvil lit from within, distant, dusk",
    "Lightning branching across a night sky over open country",
    "Rain sweeping visibly across a lake toward the camera, grey light",
    "A rainbow forming over wet fields as the sun breaks through",
    "Sunbeams breaking through cloud onto the sea, high contrast",
    "A sunset burning orange behind silhouetted hills, clouds moving",
    "The last light fading from a mountain face, cold blue shadow rising",
    "Stars wheeling slowly above a dark treeline, deep night",
    "The Milky Way over a still desert horizon, faint airglow",
    "A full moon rising behind bare winter branches, cold light",
    "Moonlight on rippling water, silver path, dark surround",
    "Dawn light spreading across a frozen lake, pink to gold",
    "A meadow of wildflowers moving in the wind, hazy summer sun",
    "Poppies in a green field bending in a gust, bright overcast",
    "A hillside of heather in flower, low cloud drifting over",
    "Bluebells covering a woodland floor, dappled spring light",
    "Long grass bending in waves across a hillside, low golden sun",
    "A bamboo grove swaying, green filtered light, quiet",
    "Aspen leaves trembling in a breeze, bright autumn yellow",
    "Birch trunks white against dark forest, snow on the ground",
    "A single oak in a field with cloud shadows passing over it",
    "Moss and ferns on a damp forest floor, soft green light",
    "Mushrooms on a fallen log, shallow focus, dim forest light",
    "Mist hanging between conifers at first light, still air",
    "Rain dripping from a leaf canopy, forest floor dark, green light",
    "Sunlight moving across a forest floor as clouds pass",
    "A stream running under exposed tree roots, dappled light",
    "A beaver dam holding back a still pond, evening light",
    "A reed bed moving in the wind at the edge of a lake, grey light",
    "Water lilies on a still pond, insects skimming the surface",
    "A mountain tarn perfectly reflecting the ridge above, still dawn",
    "A river braiding across a gravel plain, seen wide, flat light",
    "Rapids breaking white over boulders, spray, bright daylight",
    "A waterfall plunging into a dark plunge pool, mist rising",
    "A tidal estuary at low water, channels shining, wide grey sky",
    "Waves breaking over a reef, spray blown back by offshore wind",
    "A big swell rolling in under grey cloud, no horizon detail",
    "Foam sliding back down a steep shingle beach, low sun",
    "Rock pools reflecting the sky at low tide, bright light",
    "Kelp moving in the surge in shallow clear water",
    "Sea caves with light reflecting off the water onto the walls",
    "A sea stack with waves washing around its base, evening light",
    "Cliffs with seabirds wheeling below the top, bright overcast",
    "A lighthouse beam sweeping through sea mist at night",
    "A calm sea at dawn with no wind, pale gradient sky",
    "Sunlight sparkling on choppy water, high contrast, hard light",
    "A coral reef in shallow water, light rippling across it",
    "Seagrass bending with the current, clear turquoise water",
    "Rain dimpling the surface of a tropical lagoon, warm grey light",
    "A mangrove root system in shallow water, dappled light",
    "A salt marsh with channels filling on the tide, wide flat light",
    "Sand ripples underwater with light patterns moving over them",
    "A field of ripe barley moving in the wind, warm evening light",
    "A vineyard on a slope with mist in the rows at dawn",
    "An olive grove with silver leaves turning in the wind, hard sun",
    "A tea plantation on terraced hills, low cloud, soft light",
    "Rice paddies reflecting the sky, a slight breeze, flat light",
    "A field of tulips in blocks of colour, bright overcast",
    "An orchard in blossom with petals drifting down, soft sun",
    "A hedgerow in autumn heavy with berries, low golden light",
    "A stubble field after harvest with dust blowing, hard sun",
    "A ploughed field with gulls following, grey winter light",
    "A hay meadow with insects in the air, backlit summer light",
    "A pumpkin field in October, low sun, long shadows",
    "A cotton field with bolls moving in the wind, bright light",
    "Sunflowers turning toward the light, blue sky, scattered cloud",
    "A lavender row with bees working along it, hazy sun",
    "A greenhouse interior with condensation running down the glass",
    "Seedlings in trays with water droplets on the leaves, soft light",
    "A compost heap steaming faintly in cold morning air",
    "A garden pond with insects landing on the surface, dappled light",
    "Ivy moving slightly on an old stone wall, overcast light",
    "Cherry blossom against a grey sky, petals falling",
    "Autumn leaves turning on a single maple, wind picking up",
    "Bare branches against a white winter sky, snow beginning",
    "Buds opening on a branch in early spring, soft light",
    "A wildfire smoke haze turning the sun deep orange, dim light",
    "Fresh snow untouched on a hillside at first light, blue shadows",
    "A hail shower bouncing off a stone path, hard bright light",
    "Wind flattening long grass in gusts across a headland",
    "Dew on a spider web catching the low morning sun",
    "Frost patterns on a fallen leaf, cold shallow light",
    "A puddle freezing over, ice crystals spreading, dull light",
    "Sea smoke rising off water on a freezing morning, low sun",
    "A sandstorm approaching across flat desert, dimming the light",
    "A meteor streaking across a dark star field, brief",
    "Clouds racing across the moon, light coming and going",
    "Bioluminescence glowing in breaking waves at night",
    "A tide pool at dusk reflecting the last colour in the sky",
    "Sun setting directly into the sea, path of light on the water",
    "A high alpine glacier under hard blue sky, wind blowing snow",
    "A crevasse field seen from above, deep blue shadow",
    "A mountain hut with cloud streaming past, cold flat light",
    "Scree slope with small stones sliding, hard midday sun",
    "An alpine meadow with flowers below a snow peak, bright light",
    "A rock face with water seeping and dripping, shaded",
    "Wind-carved rock formations in a desert, low raking light",
    "A limestone pavement with grass in the cracks, grey light",
    "A peat bog with cotton grass moving in the wind, flat light",
    "A chalk stream running clear over weed, bright dappled light",
    "A weir with water pouring evenly over the lip, grey light",
    "A canal reflecting overhanging trees, still, soft light",
    "A flooded field with trees standing in water, grey calm light",
    "A river in spate carrying branches, brown water, overcast",
    "A dry riverbed with cracked mud, hard sun, heat shimmer",
    "A spring bubbling up through sand, clear water, dappled light",
    "A waterfall seen from behind through the falling curtain",
    "Rain on a tin roof seen from beneath the eaves, grey light",
    "A storm passing and light returning across a valley",
]

# ---------------------------------------------------------------------- urban
URBAN_EXT = [
    "A cobbled street in the rain at night, single streetlamp, reflections",
    "A wide avenue at dawn with almost no traffic, low sun down the street",
    "A crossing signal changing and a few people stepping off the kerb",
    "A revolving door turning slowly in a lobby, bright exterior behind",
    "An escalator moving in an empty station concourse, cool light",
    "A lift lobby with floor indicators changing, polished stone, even light",
    "A parking garage with a car's headlights sweeping the pillars",
    "A loading bay with a shutter rolling up, harsh sodium light",
    "A fire escape on a brick wall with steam drifting past, night",
    "A back alley with a single door light and rain falling",
    "A laundrette at night with machines turning, fluorescent light",
    "A late-night diner window seen from the street, warm interior",
    "A bar interior with bottles backlit, dim and warm, quiet",
    "A cinema foyer with carpet and dim wall lights, empty",
    "A theatre auditorium with house lights slowly dimming",
    "A concert hall stage empty with a single work light",
    "A museum gallery with light from a high window across a floor",
    "An art gallery corridor with spotlit walls, polished concrete",
    "A cathedral nave with light falling through clerestory windows",
    "A mosque interior with patterned light on the carpet",
    "A temple courtyard with incense smoke drifting, warm light",
    "A synagogue interior with warm lamps and wooden benches",
    "A university quad with long shadows in late afternoon",
    "A school corridor empty between classes, fluorescent light",
    "A hospital corridor with a trolley passing, cool even light",
    "An office floor after hours with a few desk lamps still on",
    "A server room with rows of blinking lights, cold blue glow",
    "A control room with banks of monitors, dim surround",
    "A print works with a press running, harsh industrial light",
    "A warehouse aisle with a forklift moving away, high bay lights",
    "A shipping container yard with a crane moving, hard daylight",
    "A dockside with a ship's hull filling the frame, grey light",
    "A fishing harbour at dawn with boats returning, soft light",
    "A marina with halyards moving and reflections shifting, bright light",
    "A canal lock filling slowly, water churning, overcast",
    "A railway yard with wagons being shunted, flat grey light",
    "A level crossing with barriers lowering, evening light",
    "A tram stop with a tram arriving, wet road, night",
    "A bus depot with buses idling, exhaust visible, cold morning",
    "An airport gate with a plane pushing back beyond the glass",
    "A runway seen through heat haze, aircraft taxiing, hard sun",
    "A motorway bridge with traffic streaming beneath at dusk",
    "A toll booth at night with headlights approaching, sodium light",
    "A petrol station forecourt at night, bright canopy, dark surround",
    "A car wash with brushes and water on the windscreen from inside",
    "A multi-storey rooftop car park at sunset, city beyond",
    "A construction site with a crane slewing slowly, bright sky",
    "Scaffolding on a building facade with sheeting moving in the wind",
    "A demolition site with dust settling, hard afternoon light",
    "A newly poured concrete floor being smoothed, work lights",
    "A road crew laying tarmac, steam rising, bright daylight",
    "A window cleaner's cradle moving down a glass facade",
    "A city square with pigeons and a fountain running, bright light",
    "A fountain switching off and the water settling, evening",
    "A park bandstand empty with leaves blowing across, autumn light",
    "A municipal rose garden with a sprinkler turning, bright sun",
    "A cemetery with long shadows between stones, low winter sun",
    "A canal towpath with a narrowboat passing slowly, soft light",
    "A pedestrian bridge with the river running below, grey light",
    "A riverside walk at blue hour with lights coming on",
    "A skyline seen across water with lights reflecting, dusk",
    "A rooftop garden with plants moving in the wind, city behind",
    "A balcony with washing drying and traffic sound implied, warm light",
    "An apartment block facade with lights on in some windows, night",
    "A stairwell with light falling from a high window, dust in the air",
    "A hotel corridor with patterned carpet and wall sconces",
    "A hotel room window with curtains moving and city beyond",
    "A launderette window seen from outside at night, warm inside",
    "A bakery window with trays being filled from behind, morning",
    "A butcher's shop with a counter light and hanging scales",
    "A greengrocer arranging crates on the pavement, bright morning",
    "A flower stall with buckets of stems, awning shadow, bright light",
    "A fish market slab with ice and a hose running, cold light",
    "A spice market with sacks open, warm dusty light",
    "A night market with hanging bulbs and steam, warm and dark",
    "A food truck window with steam and a warm interior light, night",
    "A vending machine glowing in an empty passage at night",
    "A phone box lit from within on an empty street",
    "A bus shelter with rain running down the glass, night",
    "A pedestrian underpass with tiled walls and a strip light",
    "A graffiti wall with paint still wet, bright daylight",
    "A mural being painted from a cherry picker, bright sky",
    "A shopfront shutter with peeling paint, hard afternoon sun",
    "A barber's pole turning outside a shop, evening light",
    "A neon sign flickering on above a doorway, dusk",
    "A cinema marquee with letters lit, rain on the pavement",
    "An arcade with machine lights and no one there, dark surround",
    "A bowling alley lane with pins resetting, low warm light",
    "A swimming pool hall empty with light rippling on the ceiling",
    "An ice rink empty with the surface being resurfaced, cold light",
    "A gym at night with one row of lights on, machines still",
    "A boxing gym with a bag swinging slightly, dusty light",
    "A dance studio empty with mirrors and a barre, north light",
    "A recording studio live room empty, warm lamps, cables",
    "A radio tower blinking on a hill at dusk, city lights below",
    "A water tower against an evening sky, birds circling",
    "A power station cooling tower with steam drifting, flat light",
    "A wind turbine turning slowly against grey cloud",
    "A solar farm with panels tracking, hard bright light",
    "An electricity pylon line receding across fields, low sun",
    "A railway tunnel mouth with a train emerging, hard contrast",
    "A metro platform with a train's lights approaching in the tunnel",
    "A ticket hall with departure boards updating, cool light",
    "A cable car ascending above a city, cabin swaying slightly",
    "A funicular climbing a steep slope, town below, bright light",
    "A ferris wheel turning slowly at dusk, lights coming on",
    "A carousel turning with lights and horses, evening",
    "A fairground at night with lights moving, dark between",
    "A pier stretching out to sea with lamps lit, blue hour",
    "A promenade with waves breaking over the sea wall, grey light",
    "A beach hut row with paint bright under a flat overcast sky",
    "A seaside arcade front at night, saturated light, wet pavement",
    "A harbour wall with waves bursting over it, storm light",
    "A coastal road with mist blowing across, headlights faint",
    "A mountain village street with snow banked at the sides",
    "A hill town at dusk with lights coming on in the houses",
    "A desert highway with heat shimmer and no traffic",
    "A dirt road with dust hanging after a vehicle has passed",
    "A tree-lined avenue with light flickering through the canopy",
]

# -------------------------------------------------------------------- objects
OBJECTS_EXT = [
    "Honey drizzling slowly from a dipper into a jar, warm backlight",
    "Milk being poured into black coffee, clouds blooming, bright light",
    "A tea bag steeping and colour spreading through hot water",
    "Butter melting in a hot pan and sliding across it",
    "Chocolate being poured into a mould, glossy, cool studio light",
    "Caramel being pulled and folded on a marble slab, warm light",
    "Cheese being sliced with a wire, clean edge, bright light",
    "Bread being torn open with steam escaping, warm light",
    "A soft-boiled egg being opened and yolk running, bright light",
    "Batter being whisked until smooth, bowl rotating, soft light",
    "Herbs being chopped finely, blade rocking, bright board",
    "Citrus being zested with a fine grater, oil misting, close",
    "Garlic being crushed under a knife blade, bright kitchen light",
    "A jar of preserves being sealed and the lid popping, warm light",
    "Popcorn popping in a covered pan, lid lifting slightly",
    "Rice being rinsed in a bowl, water clouding, bright light",
    "Noodles being lifted from broth with chopsticks, steam rising",
    "Sparkling water being poured, bubbles rising, backlit glass",
    "Wine being swirled in a glass, legs running down the side",
    "Beer being poured with a head forming, warm bar light",
    "Ice cracking as liquid is poured over it, close, dark background",
    "A cocktail being strained into a chilled glass, dim bar light",
    "A teapot pouring a thin steady stream, steam, soft light",
    "A moka pot bubbling on a hob, coffee rising, warm light",
    "An espresso extraction running into a cup, close, machine light",
    "Steam wand frothing milk, vortex forming, cafe light",
    "A kettle boiling with steam pouring from the spout, kitchen light",
    "Oil shimmering in a hot pan just before smoking",
    "A candle being lit and the flame settling, dark room",
    "A match striking and flaring, close, black background",
    "Incense smoke curling upward in still air, single beam of light",
    "A wood fire collapsing and sparks rising, dark surround",
    "Embers glowing and pulsing in a grate, dark room",
    "A gas hob ring igniting, blue flame steadying",
    "A blowtorch flame playing across metal, dark workshop",
    "Molten metal being poured into a mould, intense glow",
    "Sparks streaming from an angle grinder, dark background",
    "A welding arc flaring and dimming, deep shadow around",
    "Solder melting and flowing along a joint, bright close light",
    "A soldering iron tip being cleaned on a sponge, steam",
    "A drill bit cutting into wood, shavings spiralling out",
    "A saw blade cutting through a board, dust rising, work light",
    "A plane taking a long shaving off a board, curling away",
    "Sandpaper moving across wood, dust and changing sheen",
    "A chisel paring a shaving from end grain, bright bench light",
    "A clock's second hand sweeping, close, warm light",
    "A pendulum swinging in a case, brass catching lamp light",
    "An hourglass with sand running, backlit, dark background",
    "A metronome ticking back and forth, warm lamp",
    "A music box cylinder turning and plucking the comb, close",
    "A record needle settling into the groove, close, warm light",
    "A cassette reel turning behind a window, warm light",
    "A film projector reel turning, dust in the beam, dark booth",
    "A camera shutter opening and closing in slow motion",
    "A lens aperture blades closing down, close, studio light",
    "A typewriter key striking the page, ink impression, lamp light",
    "A fountain pen nib laying a wet line of ink, close",
    "Ink being drawn into a pen from a bottle, warm light",
    "A pencil being sharpened, shavings curling, bright light",
    "A brush loading paint from a palette, studio light",
    "Watercolour blooming into wet paper, bright even light",
    "A palette knife spreading thick paint on canvas, raking light",
    "Ink being rolled out on a slab with a brayer, even light",
    "A screen print squeegee lifting to reveal a print, bright light",
    "Clay being wedged on a bench, hands pressing, workshop light",
    "A glaze being poured over a bisque bowl, cool studio light",
    "A kiln peephole glowing orange, dark surround",
    "Thread being wound onto a bobbin, close, task light",
    "A needle pulling thread through fabric, close, lamp light",
    "Scissors cutting a long clean line through fabric, bright light",
    "A knot being tied in rope, hands working, flat light",
    "A shoelace being threaded and pulled tight, close",
    "Wool being spun onto a spindle, fibre drawing out, warm light",
    "A loom shuttle passing and the beater knocking up, workshop light",
    "Dye spreading through white fabric in a bath, overhead light",
    "Fabric being steamed and creases falling out, backlit",
    "A paper sheet being folded sharply, crisp edge, bright light",
    "A book page turning in a draught, warm reading light",
    "Dust motes drifting through a shaft of light in a still room",
    "Rain running down a window pane, lights beyond out of focus",
    "Condensation forming on a cold glass, drops beginning to run",
    "Soap bubbles forming and popping in a sink, bright light",
    "Water swirling down a drain, close, bright light",
    "A drop falling into still water, crown and ripples, dark background",
    "Oil and water separating in a jar, backlit, slow motion",
    "Sand running through fingers onto a pile, low sun",
    "A magnet dragging iron filings into lines, bright even light",
    "A pendulum of a Newton's cradle clicking, warm desk light",
    "A spinning top slowing and beginning to wobble, dark surface",
    "A domino line falling in sequence, bright even light",
    "A balloon slowly deflating, surface wrinkling, plain background",
    "A feather falling slowly through still air, dark background",
    "A soap film shifting colours across a wire loop, dark surround",
    "Frost melting off a windscreen in the morning sun",
]

EXT_ALL = PEOPLE_EXT + ANIMALS_EXT + NATURE_EXT + URBAN_EXT + OBJECTS_EXT

# One in-place substitution in the ORIGINAL bank. Index 20 was
# "A child blowing bubbles in a garden" -- this bank is to contain no minors,
# and deleting the entry instead of replacing it would renumber prompts 21-95
# and silently break world_p44 (owl), world_p60 (waterfall) and world_p82
# (court), which are referenced by index everywhere in FINDINGS and by
# `demo.py --prompt-idx`. Substituting the text keeps every index where it was.
#
# Consequence to act on: the six teacher clips already generated for prompt 20
# (`data/teacher/p0020_s0*.pt`) were made from the old text and must be deleted
# so `gen_teacher.py` regenerates them. Nothing else is affected.
REPLACEMENTS = {
    20: "A woman blowing bubbles in a garden, sunlight through the bubbles, summer afternoon",
}

# Words that would indicate a minor in a prompt. Checked against the FINAL bank,
# so it covers the original 96 as well as the extension -- a convention that is
# only written down in a docstring is one nobody notices breaking.
_MINOR_TERMS = (
    'child', 'children', 'kid', 'kids', 'boy', 'girl', 'toddler', 'baby',
    'babies', 'infant', 'teen', 'teenage', 'teenager', 'youngster', 'schoolboy',
    'schoolgirl', 'schoolchild', 'pupil', 'playground', 'nursery', 'daughter',
    'son', 'juvenile', 'minor', 'adolescent', 'youth', 'newborn', 'grandchild',
)


def assert_no_minors(prompts):
    """Raise if any prompt reads as depicting a minor. Word-boundary matched, so
    'person' does not trip 'son' and 'stonemason' does not trip it either."""
    import re
    pat = re.compile(r'\b(' + '|'.join(_MINOR_TERMS) + r')\b', re.I)
    bad = [(i, p) for i, p in enumerate(prompts) if pat.search(p)]
    if bad:
        raise AssertionError(
            f'{len(bad)} prompt(s) reference a minor; this bank must contain '
            f'none. First: index {bad[0][0]} -- {bad[0][1]!r}')
    return True
